### ISSUE TITLE
invalid read from device buffer

### ISSUE THREAD

**Issue by raffenet** [mpi-forum/mem-alloc#21]
https://github.com/mpi-forum/mem-alloc/blob/f29b0e28ab7e82f619a6e35b2583a084c3602aa9/examples-src/mem_alloc_cuda_example.cpp#L167

This device buffer access is invalid from the CPU. Either the `MPI_Allreduce` should use `system_buf` for the recv buffer, or the contents need to be copied to the CPU before asserting the value.

**Comment by rzambre** [comment]
We'd want the `MPI_Allreduce` to use `device_buf`. So, the latter option that your PR does would be the right fix.
