### ISSUE TITLE
Communicator cuda_comm was not declared in the CUDA sample

### ISSUE THREAD

**Issue by amirsojoodi** [mpi-forum/mem-alloc#4]
The communicator `cuda_comm` in this [line](https://github.com/mpi-forum/mem-alloc/blob/352618063ca25890b0179d6fe1865fde1577956b/mem_alloc.tex#L296) was not declared. 

```c
// Perform communication using cuda_comm
// if it's available.
MPI_Allreduce(MPI_IN_PLACE, device_buf, 1, MPI_INT,
              MPI_SUM, cuda_comm);

```

**Comment by rzambre** [comment]
Thank you for catching it. Fixed it in this commit -- https://github.com/mpi-forum/mem-alloc/commit/79e90170af2dbb67b7663eed67799f25c5f1e759
